#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v3
# autospec commit: c1050fe
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : khelpcenter
Version  : 23.08.3
Release  : 62
URL      : https://download.kde.org/stable/release-service/23.08.3/src/khelpcenter-23.08.3.tar.xz
Source0  : https://download.kde.org/stable/release-service/23.08.3/src/khelpcenter-23.08.3.tar.xz
Source1  : https://download.kde.org/stable/release-service/23.08.3/src/khelpcenter-23.08.3.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.2 GPL-2.0 GPL-3.0
Requires: khelpcenter-bin = %{version}-%{release}
Requires: khelpcenter-data = %{version}-%{release}
Requires: khelpcenter-license = %{version}-%{release}
Requires: khelpcenter-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : grantlee-dev
BuildRequires : khtml-dev
BuildRequires : kjs-dev
BuildRequires : libxml2-dev
BuildRequires : xapian-core-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
KHelpCenter documentation meta data structure
=============================================

%package bin
Summary: bin components for the khelpcenter package.
Group: Binaries
Requires: khelpcenter-data = %{version}-%{release}
Requires: khelpcenter-license = %{version}-%{release}

%description bin
bin components for the khelpcenter package.


%package data
Summary: data components for the khelpcenter package.
Group: Data

%description data
data components for the khelpcenter package.


%package doc
Summary: doc components for the khelpcenter package.
Group: Documentation

%description doc
doc components for the khelpcenter package.


%package license
Summary: license components for the khelpcenter package.
Group: Default

%description license
license components for the khelpcenter package.


%package locales
Summary: locales components for the khelpcenter package.
Group: Default

%description locales
locales components for the khelpcenter package.


%prep
%setup -q -n khelpcenter-23.08.3
cd %{_builddir}/khelpcenter-23.08.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1701989559
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1701989559
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/khelpcenter
cp %{_builddir}/khelpcenter-%{version}/LICENSES/GFDL-1.2-or-later.txt %{buildroot}/usr/share/package-licenses/khelpcenter/7697008f58568e61e7598e796eafc2a997503fde || :
cp %{_builddir}/khelpcenter-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/khelpcenter/3e8971c6c5f16674958913a94a36b1ea7a00ac46 || :
cp %{_builddir}/khelpcenter-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/khelpcenter/3e8971c6c5f16674958913a94a36b1ea7a00ac46 || :
cp %{_builddir}/khelpcenter-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/khelpcenter/2123756e0b1fc8243547235a33c0fcabfe3b9a51 || :
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build
%make_install
popd
%find_lang khelpcenter5
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/V3/usr/lib64/libexec/khc_xapianindexer
/V3/usr/lib64/libexec/khc_xapiansearch
/usr/lib64/libexec/khc_mansearch.pl
/usr/lib64/libexec/khc_xapianindexer
/usr/lib64/libexec/khc_xapiansearch

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/khelpcenter
/usr/bin/khelpcenter

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.khelpcenter.desktop
/usr/share/config.kcfg/khelpcenter.kcfg
/usr/share/dbus-1/services/org.kde.khelpcenter.service
/usr/share/kde4/services/khelpcenter.desktop
/usr/share/khelpcenter/glossary.xslt
/usr/share/khelpcenter/plugins/Applications/.directory
/usr/share/khelpcenter/plugins/Manpages/.directory
/usr/share/khelpcenter/plugins/Manpages/man1.desktop
/usr/share/khelpcenter/plugins/Manpages/man2.desktop
/usr/share/khelpcenter/plugins/Manpages/man3.desktop
/usr/share/khelpcenter/plugins/Manpages/man4.desktop
/usr/share/khelpcenter/plugins/Manpages/man5.desktop
/usr/share/khelpcenter/plugins/Manpages/man6.desktop
/usr/share/khelpcenter/plugins/Manpages/man7.desktop
/usr/share/khelpcenter/plugins/Manpages/man8.desktop
/usr/share/khelpcenter/plugins/Scrollkeeper/.directory
/usr/share/khelpcenter/plugins/fundamentals.desktop
/usr/share/khelpcenter/plugins/info.desktop
/usr/share/khelpcenter/plugins/kcontrolmodules.desktop
/usr/share/khelpcenter/plugins/kicmodules.desktop
/usr/share/khelpcenter/plugins/kioworkers.desktop
/usr/share/khelpcenter/plugins/onlinehelp.desktop
/usr/share/khelpcenter/plugins/plasma.desktop
/usr/share/khelpcenter/searchhandlers/man.desktop
/usr/share/khelpcenter/searchhandlers/xapian.desktop
/usr/share/khelpcenter/table-of-contents.xslt
/usr/share/khelpcenter/templates/glossary.html
/usr/share/khelpcenter/templates/index.html
/usr/share/khelpcenter/templates/search.html
/usr/share/kservices5/khelpcenter.desktop
/usr/share/metainfo/org.kde.khelpcenter.metainfo.xml
/usr/share/qlogging-categories5/khelpcenter.categories

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/fundamentals/colors.png
/usr/share/doc/HTML/ca/fundamentals/config.docbook
/usr/share/doc/HTML/ca/fundamentals/files-locationbar-breadcrumb.png
/usr/share/doc/HTML/ca/fundamentals/files-locationbar-context-menu.png
/usr/share/doc/HTML/ca/fundamentals/files-locationbar-editable.png
/usr/share/doc/HTML/ca/fundamentals/files-locationbar-places-icon.png
/usr/share/doc/HTML/ca/fundamentals/files-open.png
/usr/share/doc/HTML/ca/fundamentals/files-save.png
/usr/share/doc/HTML/ca/fundamentals/find-find-inline.png
/usr/share/doc/HTML/ca/fundamentals/find-replace-inline.png
/usr/share/doc/HTML/ca/fundamentals/fonts.png
/usr/share/doc/HTML/ca/fundamentals/index.cache.bz2
/usr/share/doc/HTML/ca/fundamentals/index.docbook
/usr/share/doc/HTML/ca/fundamentals/install.docbook
/usr/share/doc/HTML/ca/fundamentals/menus.png
/usr/share/doc/HTML/ca/fundamentals/shortcuts-schemes.png
/usr/share/doc/HTML/ca/fundamentals/shortcuts-set.png
/usr/share/doc/HTML/ca/fundamentals/tasks.docbook
/usr/share/doc/HTML/ca/fundamentals/toolbars-configure.png
/usr/share/doc/HTML/ca/fundamentals/toolbars-toolbar.png
/usr/share/doc/HTML/ca/fundamentals/ui.docbook
/usr/share/doc/HTML/ca/fundamentals/visualdict-breadcrumb.png
/usr/share/doc/HTML/ca/fundamentals/visualdict-button.png
/usr/share/doc/HTML/ca/fundamentals/visualdict-color-selector.png
/usr/share/doc/HTML/ca/fundamentals/visualdict-combo-box.png
/usr/share/doc/HTML/ca/fundamentals/visualdict-context-menu.png
/usr/share/doc/HTML/ca/fundamentals/visualdict-dialog-box.png
/usr/share/doc/HTML/ca/fundamentals/visualdict-drop-down-box.png
/usr/share/doc/HTML/ca/khelpcenter/glossary/index.cache.bz2
/usr/share/doc/HTML/ca/khelpcenter/glossary/index.docbook
/usr/share/doc/HTML/ca/khelpcenter/glossary/kdeprintingglossary.docbook
/usr/share/doc/HTML/ca/khelpcenter/index.cache.bz2
/usr/share/doc/HTML/ca/khelpcenter/index.docbook
/usr/share/doc/HTML/ca/onlinehelp/index.cache.bz2
/usr/share/doc/HTML/ca/onlinehelp/index.docbook
/usr/share/doc/HTML/ca@valencia/fundamentals/config.docbook
/usr/share/doc/HTML/ca@valencia/fundamentals/index.cache.bz2
/usr/share/doc/HTML/ca@valencia/fundamentals/index.docbook
/usr/share/doc/HTML/ca@valencia/fundamentals/install.docbook
/usr/share/doc/HTML/ca@valencia/fundamentals/tasks.docbook
/usr/share/doc/HTML/ca@valencia/fundamentals/ui.docbook
/usr/share/doc/HTML/ca@valencia/khelpcenter/glossary/index.cache.bz2
/usr/share/doc/HTML/ca@valencia/khelpcenter/glossary/index.docbook
/usr/share/doc/HTML/ca@valencia/khelpcenter/glossary/kdeprintingglossary.docbook
/usr/share/doc/HTML/ca@valencia/khelpcenter/index.cache.bz2
/usr/share/doc/HTML/ca@valencia/khelpcenter/index.docbook
/usr/share/doc/HTML/ca@valencia/onlinehelp/index.cache.bz2
/usr/share/doc/HTML/ca@valencia/onlinehelp/index.docbook
/usr/share/doc/HTML/de/fundamentals/config.docbook
/usr/share/doc/HTML/de/fundamentals/index.cache.bz2
/usr/share/doc/HTML/de/fundamentals/index.docbook
/usr/share/doc/HTML/de/fundamentals/install.docbook
/usr/share/doc/HTML/de/fundamentals/tasks.docbook
/usr/share/doc/HTML/de/fundamentals/ui.docbook
/usr/share/doc/HTML/de/khelpcenter/glossary/index.cache.bz2
/usr/share/doc/HTML/de/khelpcenter/glossary/index.docbook
/usr/share/doc/HTML/de/khelpcenter/glossary/kdeprintingglossary.docbook
/usr/share/doc/HTML/de/khelpcenter/index.cache.bz2
/usr/share/doc/HTML/de/khelpcenter/index.docbook
/usr/share/doc/HTML/de/onlinehelp/index.cache.bz2
/usr/share/doc/HTML/de/onlinehelp/index.docbook
/usr/share/doc/HTML/en/fundamentals/colors.png
/usr/share/doc/HTML/en/fundamentals/config.docbook
/usr/share/doc/HTML/en/fundamentals/files-locationbar-breadcrumb.png
/usr/share/doc/HTML/en/fundamentals/files-locationbar-context-menu.png
/usr/share/doc/HTML/en/fundamentals/files-locationbar-editable.png
/usr/share/doc/HTML/en/fundamentals/files-locationbar-places-icon.png
/usr/share/doc/HTML/en/fundamentals/files-open.png
/usr/share/doc/HTML/en/fundamentals/files-save.png
/usr/share/doc/HTML/en/fundamentals/find-find-inline.png
/usr/share/doc/HTML/en/fundamentals/find-find.png
/usr/share/doc/HTML/en/fundamentals/find-found.png
/usr/share/doc/HTML/en/fundamentals/find-replace-inline.png
/usr/share/doc/HTML/en/fundamentals/find-replace.png
/usr/share/doc/HTML/en/fundamentals/fonts.png
/usr/share/doc/HTML/en/fundamentals/index.cache.bz2
/usr/share/doc/HTML/en/fundamentals/index.docbook
/usr/share/doc/HTML/en/fundamentals/install.docbook
/usr/share/doc/HTML/en/fundamentals/menus.png
/usr/share/doc/HTML/en/fundamentals/shortcuts-schemes.png
/usr/share/doc/HTML/en/fundamentals/shortcuts-search.png
/usr/share/doc/HTML/en/fundamentals/shortcuts-set.png
/usr/share/doc/HTML/en/fundamentals/spellcheck-check.png
/usr/share/doc/HTML/en/fundamentals/tasks.docbook
/usr/share/doc/HTML/en/fundamentals/toolbars-configure.png
/usr/share/doc/HTML/en/fundamentals/toolbars-toolbar.png
/usr/share/doc/HTML/en/fundamentals/ui.docbook
/usr/share/doc/HTML/en/fundamentals/visualdict-breadcrumb.png
/usr/share/doc/HTML/en/fundamentals/visualdict-button.png
/usr/share/doc/HTML/en/fundamentals/visualdict-central-widget.png
/usr/share/doc/HTML/en/fundamentals/visualdict-check-box.png
/usr/share/doc/HTML/en/fundamentals/visualdict-color-selector.png
/usr/share/doc/HTML/en/fundamentals/visualdict-combo-box.png
/usr/share/doc/HTML/en/fundamentals/visualdict-context-menu.png
/usr/share/doc/HTML/en/fundamentals/visualdict-dialog-box.png
/usr/share/doc/HTML/en/fundamentals/visualdict-drop-down-box.png
/usr/share/doc/HTML/en/fundamentals/visualdict-gui1.png
/usr/share/doc/HTML/en/fundamentals/visualdict-gui2.png
/usr/share/doc/HTML/en/fundamentals/visualdict-gui3.png
/usr/share/doc/HTML/en/fundamentals/visualdict-gui4.png
/usr/share/doc/HTML/en/fundamentals/visualdict-icon-list.png
/usr/share/doc/HTML/en/fundamentals/visualdict-icon.png
/usr/share/doc/HTML/en/fundamentals/visualdict-list-box.png
/usr/share/doc/HTML/en/fundamentals/visualdict-menu-button.png
/usr/share/doc/HTML/en/fundamentals/visualdict-menu.png
/usr/share/doc/HTML/en/fundamentals/visualdict-menubar.png
/usr/share/doc/HTML/en/fundamentals/visualdict-panel.png
/usr/share/doc/HTML/en/fundamentals/visualdict-progress-bar.png
/usr/share/doc/HTML/en/fundamentals/visualdict-radio-button.png
/usr/share/doc/HTML/en/fundamentals/visualdict-scrollbar.png
/usr/share/doc/HTML/en/fundamentals/visualdict-slider.png
/usr/share/doc/HTML/en/fundamentals/visualdict-spin-box.png
/usr/share/doc/HTML/en/fundamentals/visualdict-statusbar.png
/usr/share/doc/HTML/en/fundamentals/visualdict-tab.png
/usr/share/doc/HTML/en/fundamentals/visualdict-text-area.png
/usr/share/doc/HTML/en/fundamentals/visualdict-text-box.png
/usr/share/doc/HTML/en/fundamentals/visualdict-titlebar.png
/usr/share/doc/HTML/en/fundamentals/visualdict-toolbar.png
/usr/share/doc/HTML/en/fundamentals/visualdict-tree-view.png
/usr/share/doc/HTML/en/fundamentals/visualdict-window.png
/usr/share/doc/HTML/en/fundamentals/visualdict-window2.png
/usr/share/doc/HTML/en/khelpcenter/background.png
/usr/share/doc/HTML/en/khelpcenter/bgtable.png
/usr/share/doc/HTML/en/khelpcenter/glossary/index.cache.bz2
/usr/share/doc/HTML/en/khelpcenter/glossary/index.docbook
/usr/share/doc/HTML/en/khelpcenter/glossary/kdeprintingglossary.docbook
/usr/share/doc/HTML/en/khelpcenter/index.cache.bz2
/usr/share/doc/HTML/en/khelpcenter/index.docbook
/usr/share/doc/HTML/en/khelpcenter/kdelogo2.png
/usr/share/doc/HTML/en/khelpcenter/khelpcenter.png
/usr/share/doc/HTML/en/khelpcenter/lines.png
/usr/share/doc/HTML/en/khelpcenter/lines2.png
/usr/share/doc/HTML/en/khelpcenter/pointers.png
/usr/share/doc/HTML/en/khelpcenter/shadow1.png
/usr/share/doc/HTML/en/onlinehelp/index.cache.bz2
/usr/share/doc/HTML/en/onlinehelp/index.docbook
/usr/share/doc/HTML/es/fundamentals/config.docbook
/usr/share/doc/HTML/es/fundamentals/index.cache.bz2
/usr/share/doc/HTML/es/fundamentals/index.docbook
/usr/share/doc/HTML/es/fundamentals/install.docbook
/usr/share/doc/HTML/es/fundamentals/tasks.docbook
/usr/share/doc/HTML/es/fundamentals/ui.docbook
/usr/share/doc/HTML/es/khelpcenter/glossary/index.cache.bz2
/usr/share/doc/HTML/es/khelpcenter/glossary/index.docbook
/usr/share/doc/HTML/es/khelpcenter/glossary/kdeprintingglossary.docbook
/usr/share/doc/HTML/es/khelpcenter/index.cache.bz2
/usr/share/doc/HTML/es/khelpcenter/index.docbook
/usr/share/doc/HTML/es/onlinehelp/index.cache.bz2
/usr/share/doc/HTML/es/onlinehelp/index.docbook
/usr/share/doc/HTML/it/fundamentals/colors.png
/usr/share/doc/HTML/it/fundamentals/config.docbook
/usr/share/doc/HTML/it/fundamentals/files-locationbar-context-menu.png
/usr/share/doc/HTML/it/fundamentals/files-open.png
/usr/share/doc/HTML/it/fundamentals/files-save.png
/usr/share/doc/HTML/it/fundamentals/find-find-inline.png
/usr/share/doc/HTML/it/fundamentals/find-find.png
/usr/share/doc/HTML/it/fundamentals/find-found.png
/usr/share/doc/HTML/it/fundamentals/find-replace-inline.png
/usr/share/doc/HTML/it/fundamentals/find-replace.png
/usr/share/doc/HTML/it/fundamentals/fonts.png
/usr/share/doc/HTML/it/fundamentals/index.cache.bz2
/usr/share/doc/HTML/it/fundamentals/index.docbook
/usr/share/doc/HTML/it/fundamentals/install.docbook
/usr/share/doc/HTML/it/fundamentals/menus.png
/usr/share/doc/HTML/it/fundamentals/shortcuts-schemes.png
/usr/share/doc/HTML/it/fundamentals/shortcuts-search.png
/usr/share/doc/HTML/it/fundamentals/shortcuts-set.png
/usr/share/doc/HTML/it/fundamentals/spellcheck-check.png
/usr/share/doc/HTML/it/fundamentals/tasks.docbook
/usr/share/doc/HTML/it/fundamentals/toolbars-configure.png
/usr/share/doc/HTML/it/fundamentals/toolbars-toolbar.png
/usr/share/doc/HTML/it/fundamentals/ui.docbook
/usr/share/doc/HTML/it/fundamentals/visualdict-gui1.png
/usr/share/doc/HTML/it/fundamentals/visualdict-gui2.png
/usr/share/doc/HTML/it/fundamentals/visualdict-gui3.png
/usr/share/doc/HTML/it/fundamentals/visualdict-gui4.png
/usr/share/doc/HTML/it/fundamentals/visualdict-panel.png
/usr/share/doc/HTML/it/fundamentals/visualdict-window.png
/usr/share/doc/HTML/it/fundamentals/visualdict-window2.png
/usr/share/doc/HTML/it/khelpcenter/glossary/index.cache.bz2
/usr/share/doc/HTML/it/khelpcenter/glossary/index.docbook
/usr/share/doc/HTML/it/khelpcenter/glossary/kdeprintingglossary.docbook
/usr/share/doc/HTML/it/khelpcenter/index.cache.bz2
/usr/share/doc/HTML/it/khelpcenter/index.docbook
/usr/share/doc/HTML/it/onlinehelp/index.cache.bz2
/usr/share/doc/HTML/it/onlinehelp/index.docbook
/usr/share/doc/HTML/nl/fundamentals/config.docbook
/usr/share/doc/HTML/nl/fundamentals/index.cache.bz2
/usr/share/doc/HTML/nl/fundamentals/index.docbook
/usr/share/doc/HTML/nl/fundamentals/install.docbook
/usr/share/doc/HTML/nl/fundamentals/tasks.docbook
/usr/share/doc/HTML/nl/fundamentals/ui.docbook
/usr/share/doc/HTML/nl/khelpcenter/glossary/index.cache.bz2
/usr/share/doc/HTML/nl/khelpcenter/glossary/index.docbook
/usr/share/doc/HTML/nl/khelpcenter/glossary/kdeprintingglossary.docbook
/usr/share/doc/HTML/nl/khelpcenter/index.cache.bz2
/usr/share/doc/HTML/nl/khelpcenter/index.docbook
/usr/share/doc/HTML/nl/onlinehelp/index.cache.bz2
/usr/share/doc/HTML/nl/onlinehelp/index.docbook
/usr/share/doc/HTML/pt/khelpcenter/glossary/index.cache.bz2
/usr/share/doc/HTML/pt/khelpcenter/glossary/index.docbook
/usr/share/doc/HTML/pt/khelpcenter/glossary/kdeprintingglossary.docbook
/usr/share/doc/HTML/pt_BR/fundamentals/config.docbook
/usr/share/doc/HTML/pt_BR/fundamentals/files-locationbar-breadcrumb.png
/usr/share/doc/HTML/pt_BR/fundamentals/files-locationbar-context-menu.png
/usr/share/doc/HTML/pt_BR/fundamentals/files-locationbar-editable.png
/usr/share/doc/HTML/pt_BR/fundamentals/files-locationbar-places-icon.png
/usr/share/doc/HTML/pt_BR/fundamentals/files-open.png
/usr/share/doc/HTML/pt_BR/fundamentals/files-save.png
/usr/share/doc/HTML/pt_BR/fundamentals/find-find-inline.png
/usr/share/doc/HTML/pt_BR/fundamentals/find-find.png
/usr/share/doc/HTML/pt_BR/fundamentals/find-found.png
/usr/share/doc/HTML/pt_BR/fundamentals/find-replace-inline.png
/usr/share/doc/HTML/pt_BR/fundamentals/find-replace.png
/usr/share/doc/HTML/pt_BR/fundamentals/index.cache.bz2
/usr/share/doc/HTML/pt_BR/fundamentals/index.docbook
/usr/share/doc/HTML/pt_BR/fundamentals/install.docbook
/usr/share/doc/HTML/pt_BR/fundamentals/menus.png
/usr/share/doc/HTML/pt_BR/fundamentals/shortcuts-schemes.png
/usr/share/doc/HTML/pt_BR/fundamentals/shortcuts-search.png
/usr/share/doc/HTML/pt_BR/fundamentals/shortcuts-set.png
/usr/share/doc/HTML/pt_BR/fundamentals/tasks.docbook
/usr/share/doc/HTML/pt_BR/fundamentals/toolbars-configure.png
/usr/share/doc/HTML/pt_BR/fundamentals/toolbars-toolbar.png
/usr/share/doc/HTML/pt_BR/fundamentals/ui.docbook
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-breadcrumb.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-button.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-check-box.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-combo-box.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-context-menu.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-dialog-box.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-drop-down-box.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-icon-list.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-icon.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-list-box.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-menu-button.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-menu.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-menubar.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-panel.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-radio-button.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-scrollbar.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-slider.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-spin-box.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-statusbar.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-tab.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-text-box.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-titlebar.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-toolbar.png
/usr/share/doc/HTML/pt_BR/fundamentals/visualdict-tree-view.png
/usr/share/doc/HTML/pt_BR/khelpcenter/glossary/index.cache.bz2
/usr/share/doc/HTML/pt_BR/khelpcenter/glossary/index.docbook
/usr/share/doc/HTML/pt_BR/khelpcenter/glossary/kdeprintingglossary.docbook
/usr/share/doc/HTML/pt_BR/khelpcenter/index.cache.bz2
/usr/share/doc/HTML/pt_BR/khelpcenter/index.docbook
/usr/share/doc/HTML/pt_BR/onlinehelp/index.cache.bz2
/usr/share/doc/HTML/pt_BR/onlinehelp/index.docbook
/usr/share/doc/HTML/ru/fundamentals/colors.png
/usr/share/doc/HTML/ru/fundamentals/config.docbook
/usr/share/doc/HTML/ru/fundamentals/files-locationbar-breadcrumb.png
/usr/share/doc/HTML/ru/fundamentals/files-locationbar-context-menu.png
/usr/share/doc/HTML/ru/fundamentals/files-locationbar-editable.png
/usr/share/doc/HTML/ru/fundamentals/files-locationbar-places-icon.png
/usr/share/doc/HTML/ru/fundamentals/files-open.png
/usr/share/doc/HTML/ru/fundamentals/find-find-inline.png
/usr/share/doc/HTML/ru/fundamentals/find-find.png
/usr/share/doc/HTML/ru/fundamentals/find-found.png
/usr/share/doc/HTML/ru/fundamentals/find-replace-inline.png
/usr/share/doc/HTML/ru/fundamentals/find-replace.png
/usr/share/doc/HTML/ru/fundamentals/fonts.png
/usr/share/doc/HTML/ru/fundamentals/index.cache.bz2
/usr/share/doc/HTML/ru/fundamentals/index.docbook
/usr/share/doc/HTML/ru/fundamentals/install.docbook
/usr/share/doc/HTML/ru/fundamentals/menus.png
/usr/share/doc/HTML/ru/fundamentals/shortcuts-schemes.png
/usr/share/doc/HTML/ru/fundamentals/shortcuts-search.png
/usr/share/doc/HTML/ru/fundamentals/shortcuts-set.png
/usr/share/doc/HTML/ru/fundamentals/spellcheck-check.png
/usr/share/doc/HTML/ru/fundamentals/tasks.docbook
/usr/share/doc/HTML/ru/fundamentals/toolbars-configure.png
/usr/share/doc/HTML/ru/fundamentals/toolbars-toolbar.png
/usr/share/doc/HTML/ru/fundamentals/ui.docbook
/usr/share/doc/HTML/ru/fundamentals/visualdict-breadcrumb.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-button.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-central-widget.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-color-selector.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-combo-box.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-context-menu.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-dialog-box.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-drop-down-box.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-gui1.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-gui2.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-gui3.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-icon-list.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-icon.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-menu-button.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-menu.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-menubar.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-panel.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-statusbar.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-tab.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-text-area.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-text-box.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-titlebar.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-tree-view.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-window.png
/usr/share/doc/HTML/ru/fundamentals/visualdict-window2.png
/usr/share/doc/HTML/ru/khelpcenter/glossary/index.cache.bz2
/usr/share/doc/HTML/ru/khelpcenter/glossary/index.docbook
/usr/share/doc/HTML/ru/khelpcenter/glossary/kdeprintingglossary.docbook
/usr/share/doc/HTML/ru/khelpcenter/index.cache.bz2
/usr/share/doc/HTML/ru/khelpcenter/index.docbook
/usr/share/doc/HTML/ru/onlinehelp/index.cache.bz2
/usr/share/doc/HTML/ru/onlinehelp/index.docbook
/usr/share/doc/HTML/sr/khelpcenter/index.cache.bz2
/usr/share/doc/HTML/sr/khelpcenter/index.docbook
/usr/share/doc/HTML/sr/onlinehelp/index.cache.bz2
/usr/share/doc/HTML/sr/onlinehelp/index.docbook
/usr/share/doc/HTML/sr@latin/khelpcenter/index.cache.bz2
/usr/share/doc/HTML/sr@latin/khelpcenter/index.docbook
/usr/share/doc/HTML/sr@latin/onlinehelp/index.cache.bz2
/usr/share/doc/HTML/sr@latin/onlinehelp/index.docbook
/usr/share/doc/HTML/sv/fundamentals/config.docbook
/usr/share/doc/HTML/sv/fundamentals/index.cache.bz2
/usr/share/doc/HTML/sv/fundamentals/index.docbook
/usr/share/doc/HTML/sv/fundamentals/install.docbook
/usr/share/doc/HTML/sv/fundamentals/tasks.docbook
/usr/share/doc/HTML/sv/fundamentals/ui.docbook
/usr/share/doc/HTML/sv/khelpcenter/glossary/index.cache.bz2
/usr/share/doc/HTML/sv/khelpcenter/glossary/index.docbook
/usr/share/doc/HTML/sv/khelpcenter/glossary/kdeprintingglossary.docbook
/usr/share/doc/HTML/sv/khelpcenter/index.cache.bz2
/usr/share/doc/HTML/sv/khelpcenter/index.docbook
/usr/share/doc/HTML/sv/onlinehelp/index.cache.bz2
/usr/share/doc/HTML/sv/onlinehelp/index.docbook
/usr/share/doc/HTML/uk/fundamentals/colors.png
/usr/share/doc/HTML/uk/fundamentals/config.docbook
/usr/share/doc/HTML/uk/fundamentals/files-locationbar-breadcrumb.png
/usr/share/doc/HTML/uk/fundamentals/files-locationbar-context-menu.png
/usr/share/doc/HTML/uk/fundamentals/files-locationbar-editable.png
/usr/share/doc/HTML/uk/fundamentals/files-locationbar-places-icon.png
/usr/share/doc/HTML/uk/fundamentals/files-open.png
/usr/share/doc/HTML/uk/fundamentals/files-save.png
/usr/share/doc/HTML/uk/fundamentals/find-find-inline.png
/usr/share/doc/HTML/uk/fundamentals/find-find.png
/usr/share/doc/HTML/uk/fundamentals/find-found.png
/usr/share/doc/HTML/uk/fundamentals/find-replace-inline.png
/usr/share/doc/HTML/uk/fundamentals/find-replace.png
/usr/share/doc/HTML/uk/fundamentals/fonts.png
/usr/share/doc/HTML/uk/fundamentals/index.cache.bz2
/usr/share/doc/HTML/uk/fundamentals/index.docbook
/usr/share/doc/HTML/uk/fundamentals/install.docbook
/usr/share/doc/HTML/uk/fundamentals/menus.png
/usr/share/doc/HTML/uk/fundamentals/shortcuts-schemes.png
/usr/share/doc/HTML/uk/fundamentals/shortcuts-search.png
/usr/share/doc/HTML/uk/fundamentals/shortcuts-set.png
/usr/share/doc/HTML/uk/fundamentals/spellcheck-check.png
/usr/share/doc/HTML/uk/fundamentals/tasks.docbook
/usr/share/doc/HTML/uk/fundamentals/toolbars-configure.png
/usr/share/doc/HTML/uk/fundamentals/ui.docbook
/usr/share/doc/HTML/uk/khelpcenter/glossary/index.cache.bz2
/usr/share/doc/HTML/uk/khelpcenter/glossary/index.docbook
/usr/share/doc/HTML/uk/khelpcenter/glossary/kdeprintingglossary.docbook
/usr/share/doc/HTML/uk/khelpcenter/index.cache.bz2
/usr/share/doc/HTML/uk/khelpcenter/index.docbook
/usr/share/doc/HTML/uk/onlinehelp/index.cache.bz2
/usr/share/doc/HTML/uk/onlinehelp/index.docbook

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/khelpcenter/2123756e0b1fc8243547235a33c0fcabfe3b9a51
/usr/share/package-licenses/khelpcenter/3e8971c6c5f16674958913a94a36b1ea7a00ac46
/usr/share/package-licenses/khelpcenter/7697008f58568e61e7598e796eafc2a997503fde

%files locales -f khelpcenter5.lang
%defattr(-,root,root,-)

